workflows:
  ios-build:
    name: Glucose Direct Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic
    environment:
      xcode: latest
      ios_signing:
        provisioning_profiles:
          - glucose_profile
        certificates:
          - glucose_cert
    scripts:
      - name: Strip Widget and Clean References
        script: |
          gem install xcodeproj
          # 2026 Script: Cleaned Ruby syntax to remove Widget and GUID links
          ruby -e "require 'xcodeproj'; project = Xcodeproj::Project.open('GlucoseDirect.xcodeproj'); app_target = project.targets.find { |t| t.name == 'GlucoseDirectApp' }; widget_target = project.targets.find { |t| t.name.include?('Widget') }; if app_target && widget_target; app_target.dependencies.delete_if { |d| d.target && d.target.name.include?('Widget') }; app_target.build_phases.delete_if { |p| p.display_name.include?('Embed App Extensions') }; end; project.targets.delete_if { |t| t.name.include?('Widget') }; project.save"
      - name: Generate Export Options and Build
        script: |
          xcode-project use-profiles
          xcodebuild -project GlucoseDirect.xcodeproj -scheme GlucoseDirectApp clean
          xcode-project build-ipa \
            --project "GlucoseDirect.xcodeproj" \
            --scheme "GlucoseDirectApp"
    artifacts:
      - build/ios/ipa/*.ipa
