workflows:
  ios-build:
    name: Glucose Direct Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic
    environment:
      xcode: latest
    scripts:
      - name: Initialize Keychain and Signing
        script: |
          keychain initialize
          # Create a directory to store the certificate
          mkdir -p ~/Library/MobileDevice/Certificates
          # Create certificate and force save it to the new directory
          app-store-connect certificates create --type DEVELOPMENT --save --p12-password "codemagic" --p12-path ~/Library/MobileDevice/Certificates/certificate.p12
          # Fetch the profile
          app-store-connect fetch-signing-files "com.mstry9.GlucoseDirect" --type IOS_APP_DEVELOPMENT --create --p12-password "codemagic"
          # Import the certificate into the keychain
          keychain add-certificates --p12-password "codemagic"
      - name: Install Pods
        script: |
          pod install
      - name: Build App
        script: |
          xcode-project build-ipa \
            --project "GlucoseDirect.xcodeproj" \
            --scheme "GlucoseDirect" \
            --bundle-id "com.mstry9.GlucoseDirect"
    artifacts:
      - build/ios/ipa/*.ipa
