workflows:
  ios-build:
    name: Glucose Direct Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic
    environment:
      xcode: latest
      groups:
        - glucose_vars
    scripts:
      - name: Initialize Keychain and Signing
        script: |
          keychain initialize
          # 1. Create a fresh certificate (requires an empty slot in Apple Dev Portal)
          app-store-connect certificates create --type DEVELOPMENT --save
          # 2. Corrected 2026 profile type: IOS_APP_DEVELOPMENT
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_DEVELOPMENT --create
          keychain add-certificates
      - name: Install Pods
        script: |
          pod install
      - name: Build IPA
        script: |
          # Builds the final app file
          xcode-project build-ipa \
            --project "GlucoseDirect.xcodeproj" \
            --scheme "GlucoseDirect" \
            --bundle-id "$BUNDLE_ID"
    artifacts:
      - build/ios/ipa/*.ipa
